name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout üõéÔ∏è
      uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.1'
        bundler-cache: true
    - name: Install and Build üîß
      run: |
        npm install -g mermaid.cli
        bundle exec jekyll build
    - name: Deploy üöÄ
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _site

#      run: |
#        gem install bundler
#        bundle config path vendor/bundle
#        bundle install --jobs 4 --retry 3
#    - name: Setup deploy options
#      id: setup
#      run: |
#        git config --global user.name "GitHub Action"
#        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
#        if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then # pull request
#          echo "::set-output name=SRC_BRANCH::${GITHUB_HEAD_REF}"
#          echo "::set-output name=NO_PUSH::--no-push"
#        elif [[ ${GITHUB_REF} = refs/heads/* ]]; then # branch, e.g. master, source etc
#          echo "::set-output name=SRC_BRANCH::${GITHUB_REF#refs/heads/}"
#        fi
#        if [[ ${{ github.repository }} = *.github.io ]]; then # user/org repo
#          echo "::set-output name=DEPLOY_BRANCH::master"
#        else
#          echo "::set-output name=DEPLOY_BRANCH::gh-pages"
#        fi
#    - name: Deploy website
#      run:  yes | bin/deploy --verbose ${{ steps.setup.outputs.NO_PUSH }}
#                    --src ${{ steps.setup.outputs.SRC_BRANCH }}
#                    --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}
